<a href="https://colab.research.google.com/github/Adibank/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #library เกี่ยวกับตัวเลข

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T #ทรานสโพทแมททริกซ์

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A.dot(A.T) #แมททริกซ์ A คูณกับแมททริกซ์ A ทรานสโพท

array([[14, 32],
       [32, 77]])

# Array slicing

In [ ]:
A[0,1] #[แถวที่...,หลักที่...]

2

In [ ]:
A[:,:2] #เอามาทุกแถว,เอาตั้งแต่หลักแรกจนถึงหลักที่2

In [ ]:
A[1,1:]

array([5, 6])

In [ ]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
def Manhattan_dist(dp1,dp2):
  distX = abs(dp1[0]-dp2[0])
  distY = abs(dp1[1]-dp2[1])
  return distX + distY

In [ ]:
np.zeros((4,4)) #สร้าง array เปล่า

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
7*np.ones((4,4)) #7 มาคูณ แมททริกซ์

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [ ]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

# HW6 สร้าง  Distance metrix (Euclidean) ของ data matrix ใน slides โดยสร้าง function สำหรับคำนวณ Euclidean Distance

In [ ]:
import numpy as np
import math  

In [ ]:
data2 = np.array([[1,2],[3,5],[2,0],[4,5]])

In [ ]:
data2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
  def Euclidean_dist(dp1,dp2):
    distS = abs(dp1[0]-dp2[0])
    distT = abs(dp1[1]-dp2[1])
    return math.sqrt(distS**2 + distT**2)

In [ ]:
dist_mat_Euclidean = np.zeros((4,4))
dist_mat_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
  for j in range(4):
      dist_mat_Euclidean[i,j] = Euclidean_dist(data2[i,:],data2[j,:])
dist_mat_Euclidean

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [ ]:
data2[0,:] #ทด

array([1, 2])

In [ ]:
data2[1,:] #ทด

array([3, 5])

In [ ]:
data2[0,:][0] #ทด

1

In [ ]:
data2[1,:][1] #ทด

5

# Distance of nominal or categorical features

## (extra) Python data structure (Dictionary)

In [1]:
d_A = {'a':1,2:3,3:5,'cat':6} #ใส่ได้แค่ตัวอักษรหรือตัวเลขเท่านั้น ตัวแปรใช้ไม่ได้ {ตัวชี้ : ค่าที่เก็บ}

In [2]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [3]:
d_A['cat']

6

In [6]:
d_A['dog'] = [1,2,3,4,5] #การเพิ่มสมาชิกใหม่เข้าไป

In [7]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [9]:
del d_A[2] #การลบข้อมูลออกจาก dict.

In [10]:
d_A

{3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [11]:
import pandas as pd

In [16]:
data_dict = {'color':['red','red','green'], #color = {'red','green','blue'}
             'status':['single','married','single']} #status = {'single','married','disvorced'}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [14]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

# Categorical feature distance method#1

In [17]:
list(data_pd.iloc[1,:])

['red', 'married']

In [21]:
def meth1_dist(data1,data2):
  N = 0
  print(f'data1 is {data1} and data2 is {data2}')
  for i in range(len(data1)):
    print(f'feature{i} of data1 is {data1[i]} , feature{i} of data2 is {data2[i]}')
    if data1[i] != data2[i]:
       N = N+1
       print(f' {data1[i]} is not equal {data2[i]} : updated ({N})')
    else:
       print(f' {data1[i]} is equal {data2[i]}')
  return N/len(data1)

In [22]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']
feature0 of data1 is red , feature0 of data2 is red
 red is equal red
feature1 of data1 is single , feature1 of data2 is married
 single is not equal married : updated (1)


0.5

# HW7 calculate distance matrix of data_pd using meth1_dist()

In [46]:
import numpy as np
import math  

In [48]:
def meth1_dist(data1,data2):
  N = 0
  print(f'data1 is {data1} and data2 is {data2}')
  for i in range(len(data1)):
    print(f'feature{i} of data1 is {data1[i]} , feature{i} of data2 is {data2[i]}')
    if data1[i] != data2[i]:
       N = N+1
       print(f' {data1[i]} is not equal {data2[i]} : updated ({N})')
    else:
       print(f' {data1[i]} is equal {data2[i]}')
  return N/len(data1)

In [49]:
dist_mat_data_pd = np.zeros((3,3))
dist_mat_data_pd

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
for i in range(3):
  for j in range(3):
      dist_mat_data_pd[i,j] = meth1_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))

dist_mat_data_pd

data1 is ['red', 'single'] and data2 is ['red', 'single']
feature0 of data1 is red , feature0 of data2 is red
 red is equal red
feature1 of data1 is single , feature1 of data2 is single
 single is equal single
data1 is ['red', 'single'] and data2 is ['red', 'married']
feature0 of data1 is red , feature0 of data2 is red
 red is equal red
feature1 of data1 is single , feature1 of data2 is married
 single is not equal married : updated (1)
data1 is ['red', 'single'] and data2 is ['green', 'single']
feature0 of data1 is red , feature0 of data2 is green
 red is not equal green : updated (1)
feature1 of data1 is single , feature1 of data2 is single
 single is equal single
data1 is ['red', 'married'] and data2 is ['red', 'single']
feature0 of data1 is red , feature0 of data2 is red
 red is equal red
feature1 of data1 is married , feature1 of data2 is single
 married is not equal single : updated (1)
data1 is ['red', 'married'] and data2 is ['red', 'married']
feature0 of data1 is red , feature

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])

# Categorical feature distance method#2

In [56]:
data_dict2 = {'color':['red','red','green','blue'], #color = {'red','green','blue'}
             'status':['single','married','single','disvorced']} #status = {'single','married','disvorced'}
data_pd2 = pd.DataFrame.from_dict(data_dict2)
data_pd2

color     status
0    red     single
1    red    married
2  green     single
3   blue  disvorced

In [58]:
data_pd_binary = pd.get_dummies(data_pd2)
data_pd_binary 

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1
3           1            0  ...               0              0

[4 rows x 6 columns]

In [60]:
data_pd_binary = pd.get_dummies(data_pd2)
data_pd_binary = data_pd_binary.iloc[:3,:]
data_pd_binary

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1

[3 rows x 6 columns]

In [63]:
def binary_sym_dist(data1,data2):
  r = 0
  s = 0
  t = 0
  q = 0
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      if data1[i] == 0:
        s = s + 1
      else:
        r = r + 1
    else: 
      if data1[i] == 0:
        t = t + 1
      else:
        q = q + 1

  return (r+s)/(r+s+t+q)

In [65]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.3333333333333333

# HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

In [77]:
import numpy as np
import math  

In [78]:
def binary_sym_dist(data1,data2):
  r = 0
  s = 0
  t = 0
  q = 0
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      if data1[i] == 0:
        s = s + 1
      else:
        r = r + 1
    else: 
      if data1[i] == 0:
        t = t + 1
      else:
        q = q + 1

  return (r+s)/(r+s+t+q)

In [79]:
dist_mat_data_pd = np.zeros((3,3))
dist_mat_data_pd

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
for i in range(3):
  for j in range(3):
      dist_mat_data_pd[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))

dist_mat_data_pd

array([[0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.        ]])