<a href="https://colab.research.google.com/github/Adibank/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #library เกี่ยวกับตัวเลข

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T #ทรานสโพทแมททริกซ์

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A.dot(A.T) #แมททริกซ์ A คูณกับแมททริกซ์ A ทรานสโพท

array([[14, 32],
       [32, 77]])

# Array slicing

In [ ]:
A[0,1] #[แถวที่...,หลักที่...]

2

In [ ]:
A[:,:2] #เอามาทุกแถว,เอาตั้งแต่หลักแรกจนถึงหลักที่2

In [ ]:
A[1,1:]

array([5, 6])

In [ ]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
def Manhattan_dist(dp1,dp2):
  distX = abs(dp1[0]-dp2[0])
  distY = abs(dp1[1]-dp2[1])
  return distX + distY

In [ ]:
np.zeros((4,4)) #สร้าง array เปล่า

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
7*np.ones((4,4)) #7 มาคูณ แมททริกซ์

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [ ]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

# HW6 สร้าง  Distance metrix (Euclidean) ของ data matrix ใน slides โดยสร้าง function สำหรับคำนวณ Euclidean Distance

In [89]:
import numpy as np
import math  

In [90]:
data2 = np.array([[1,2],[3,5],[2,0],[4,5]])

In [91]:
data2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [92]:
  def Euclidean_dist(dp1,dp2):
    distS = abs(dp1[0]-dp2[0])
    distT = abs(dp1[1]-dp2[1])
    return math.sqrt(distS**2 + distT**2)

In [52]:
dist_mat_Euclidean = np.zeros((4,4))
dist_mat_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
for i in range(4):
  for j in range(4):
      dist_mat_Euclidean[i,j] = Euclidean_dist(data2[i,:],data2[j,:])
dist_mat_Euclidean

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [94]:
data2[0,:] #ทด

array([1, 2])

In [95]:
data2[1,:] #ทด

array([3, 5])

In [96]:
data2[0,:][0] #ทด

1

In [97]:
data2[1,:][1] #ทด

5